language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
sudo: false
cache:
  - vendor
  - $HOME/.composer/cache
install:
  - travis_retry composer self-update
  - travis_retry composer global require fxp/composer-asset-plugin
  - travis_retry composer install
script:
  - composer exec codecept run --verbose
