language: php
branches:
  only:
    - dev
    - master
    - /^release-.*$/
php:
  - '5.6'
  - '7.0'
  - hhvm
sudo: false
cache:
  - vendor
  - $HOME/.composer/cache
install:
  - travis_retry composer self-update
  - travis_retry composer global require fxp/composer-asset-plugin
  - travis_retry composer install --prefer-dist --no-interaction
script:
  - composer exec codecept run --verbose
